# Generated by Django 4.2.7 on 2026-05-23 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CorpusStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_documents', models.IntegerField(default=0)),
                ('avg_doc_length', models.FloatField(default=1.0)),
                ('last_indexed', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Corpus Stats',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('raw_text', models.TextField()),
                ('url', models.URLField(blank=True, max_length=1000, null=True, unique=True)),
                ('pub_date', models.DateTimeField(blank=True, null=True)),
                ('file_path', models.CharField(blank=True, max_length=1000)),
                ('is_indexed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-pub_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_text', models.CharField(max_length=500)),
                ('model', models.CharField(choices=[('vsm', 'VSM'), ('bm25', 'BM25')], max_length=10)),
                ('precision_at_5', models.FloatField(blank=True, null=True)),
                ('recall_at_5', models.FloatField(blank=True, null=True)),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-evaluated_at'],
            },
        ),
        migrations.CreateModel(
            name='IndexEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(db_index=True, max_length=200, unique=True)),
                ('doc_frequency', models.IntegerField(default=0)),
                ('postings_json', models.TextField(default='{}')),
            ],
            options={
                'verbose_name_plural': 'Index Entries',
            },
        ),
        migrations.CreateModel(
            name='DocumentLength',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_count', models.IntegerField(default=0)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='length_record', to='search_app.document')),
            ],
        ),
    ]
